name: sitreps-client tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Pre-Commit Checks
        run: |
          python -m pip install pip --upgrade
          python -m pip install pre-commit
          pre-commit run -a

      - name: Analysis (git diff)
        if: failure()
        run: git diff
  test:
    name: UnitTests-Python-${{ matrix.python-version }}
    needs: [ pre-commit ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install .[test]
      - name: Test with pytest
        run: |
          pytest -v --no-cov-on-fail --cov=sitreps_client --cov-append
          mv .coverage ${{ strategy.job-index }}_coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ strategy.job-index }}_coverage
          path: ${{ strategy.job-index }}_coverage

  submit_coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
      - name: Install coverage
        run: pip install coverage
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/coverage
      - name: Combine coverage data files
        run: |
          coverage combine -a $(find /tmp/coverage -type f)
          coverage xml -o /tmp/coverage.xml
      - name: Publish coverage
        uses: codecov/codecov-action@v1.5.2
        with:
          files: /tmp/coverage.xml
